title: Rohil Kanaparti
google_scholar: https://scholar.google.com/
github_link: https://github.com/yaoyao-liu/minimal-light
linkedin: https://www.linkedin.com/in/rohilkan/
favicon: ./assets/img/""
favicon_dark: ./assets/img/""
logo: .assets/headshot_up.jpeg
theme: jekyll-theme-minimal
